-- Substans: administratorens aktivitetslog.
-- Kør denne fil i Supabase SQL Editor. Den kan køres flere gange.

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  entity_type text not null,
  entity_id text,
  summary text not null,
  created_at timestamptz not null default now()
);

alter table public.activity_log enable row level security;

drop policy if exists "Admins read activity log"
on public.activity_log;

create policy "Admins read activity log"
on public.activity_log
for select
to authenticated
using (public.is_admin());

grant select on public.activity_log to authenticated;

create index if not exists activity_log_created_idx
on public.activity_log (created_at desc);

create index if not exists activity_log_entity_idx
on public.activity_log (entity_type, created_at desc);

create or replace function public.log_substans_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
  item_summary text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  item_summary := coalesce(
    row_data->>'title',
    row_data->>'full_name',
    row_data->>'child_name',
    row_data->>'description',
    row_data->>'focus',
    replace(tg_table_name,'_',' ')
  );

  insert into public.activity_log (
    actor_profile_id,
    action,
    entity_type,
    entity_id,
    summary
  ) values (
    auth.uid(),
    tg_op,
    tg_table_name,
    row_data->>'id',
    left(item_summary,180)
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

do $$
declare
  table_name text;
  tracked_tables text[] := array[
    'applications',
    'students',
    'classes',
    'class_enrollments',
    'teachers',
    'learning_items',
    'student_feedback',
    'class_messages',
    'student_payments',
    'calendar_events',
    'curriculum_units',
    'quizzes',
    'certificates'
  ];
begin
  foreach table_name in array tracked_tables loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists substans_activity_trigger on public.%I',table_name);
      execute format(
        'create trigger substans_activity_trigger after insert or update or delete on public.%I for each row execute function public.log_substans_change()',
        table_name
      );
    end if;
  end loop;
end;
$$;
